PROFILE = {
    "name": "French",
    "rtl": False,
    "script": "latin",
    "unicode": [(0x0000, 0x024F)],
    "max_words": 10,
    "ratio": 1.15,
    "direct_pairs": {"en": (0.50, 3.5, 0.60, 1.50)},
    "opening_summary": "L'épisode vient de commencer.",
    "label_prev_context": "Contexte Précédent",
    "native_workflow_steps": {
        "header": "### [IDX_WORKFLOW]. Processus de Travail Structuré (Obligatoire - Ne pas ignorer) ###\nPour garantir une traduction précise et naturelle, vous devez suivre ces étapes dans l'ordre exact :\n\nDans le champ thought_process, écrivez votre \"processus de réflexion, stratégie et dilemmes avant la traduction finale.\" (Restez concis : 2-3 phrases max).\nDans le champ summary, écrivez un \"court résumé de ce qui se passe dans l'intrigue en ce moment.\" (Important : Ne copiez pas cette phrase ! Écrivez un vrai résumé).\nDans le champ translated_srt, saisissez les traductions finales.\nDans le champ last_speaker_info, écrivez le \"nom du dernier locuteur (M/F) s'adressant à la cible (M/F/Inconnu/Caméra).\" (Ne copiez pas l'instruction).\nDans le champ continuity_note, écrivez la \"note de continuité pour le prochain lot (laisser vide si aucune).\" (Ne copiez pas l'instruction).",
        "read_context": "Étape {n} : Lisez les textes \"Contexte Précédent\" et \"Contexte Suivant\" pour comprendre la situation. Note : Ces textes sont fournis en texte brut sans index ni horodatage (Striped Context). **Ne les traduisez pas**.",
        "priming": "Étape {n} : Écrivez un court résumé de ce qui se passe dans l'intrigue en ce moment dans le champ summary. Cela vous aidera à vous mettre en contexte avant de commencer à traduire.",
        "draft": "Étape {n} : Lisez le dictionnaire JSON sous l'en-tête [Translation Blocks - JSON]. C'est la SEULE information que vous devez traduire. Traduisez tous les textes apparaissant dans le dictionnaire comme un seul paragraphe continu, naturel et fluide en Français. Écrivez cette traduction dans le champ JSON \"continuous_translation_draft\". À ce stade, ignorez les index. Il vous est strictement interdit d'inclure des informations provenant des blocs de contexte dans le brouillon.",
        "mapping": "Étape {n} : Cartographie technique concise du brouillon vers les index, en respectant strictement la structure de la source anglaise. Exemple : 'Phrase 1 vers 14. Phrase 2 vers 15. \\n en 16. Locuteurs divisés en 17'. Ne pas expliquer, juste cartographier. Écrivez cela dans le champ \"mapping_plan\".",
        "split_rules": "Étape {n} : Sauts de ligne (\\n) - Exigence Critique :\\n1. Un sous-titre ne peut pas contenir plus de {max_words} mots sur une seule ligne. Si la traduction est longue, vous devez la diviser en deux lignes courtes et équilibrées à l'aide du caractère \\n. Vous êtes autorisé (et tenu) d'ajouter le \\n à l'intérieur des balises de formatage (ex : <i>texte... \\n ...texte</i>).\\n2. Règle des deux locuteurs : Si un sous-titre contient un dialogue entre deux personnes (indiqué par deux traits d'union -), vous devez diviser le sous-titre en deux lignes à l'aide de \\n afin que chaque locuteur ait sa propre ligne.",
        "final_srt": "Étape {n} : Saisissez le texte divisé et final dans l'objet \"translated_srt\". **Vous devez renvoyer une carte JSON (Dictionnaire) où les clés sont exactement les mêmes index numériques que vous avez reçus en entrée, et les valeurs sont les traductions finales en Français**. Assurez-vous que les noms des locuteurs (comme 'PROBST:' ou 'JEFF:' etc.) sont complètement supprimés et non traduits.",
        "metadata": "Étape {n} : Mettre à jour les métadonnées pour le prochain lot. Remplissez les champs 'last_speaker_info' et 'continuity_note' en fonction du texte que vous venez de traduire. **Attention : Ne copiez pas les phrases d'instruction entre guillemets (ex : 'nom du locuteur...') dans le résultat ! Vous devez les remplacer par les informations réelles de l'épisode.**",
        "audit": "Étape {n} : Contrôle Qualité et Références Croisées (Auto-Audit)\\nAvant de fermer le JSON, scannez attentivement l'objet translated_srt par rapport à la liste source.\\nVous devez répondre aux questions suivantes par vous-même :\\n- Tous les index existent-ils ? Assurez-vous que chaque numéro d'index apparu dans l'entrée apparaît également dans la sortie.\\n- Y a-t-il des doublons ? Vérifiez si un certain texte apparaît deux fois sous des index différents.\\n- Y a-t-il des omissions ? Assurez-vous que toutes les informations de la source ont trouvé leur place dans la traduction finale.\\n- Validité technique : Assurez-vous de ne pas avoir utilisé de barres obliques incorrectes et d'avoir uniquement utilisé \\n pour diviser les lignes."
    },
    "native_technical_rules": """### [IDX_TECH]. Règles Techniques et Formatage Visuel (CRITIQUE) ###
- Suivi du Genre : Suivez attentivement le genre des locuteurs tout au long du lot. Si plusieurs lignes consécutives appartiennent au même locuteur (ou parlent du même personnage du dictionnaire), vous devez maintenir exactement le même genre pour les adjectifs et les verbes. Ne changez pas de genre au milieu d'un paragraphe.
- Limites de Traduction : Traduisez UNIQUEMENT les valeurs apparaissant dans le dictionnaire JSON sous [Translation Blocks - JSON]. En aucun cas vous ne devez inclure de texte trouvé dans les blocs de contexte dans la traduction.
- Règle 1:1 (Précision de la carte des clés) : Vous devez renvoyer dans 'translated_srt' TOUTES les clés (index) qui sont apparues dans l'entrée. N'omettez aucune clé et n'ajoutez pas de nouvelles clés.
- Pas de Langue Source : Ne laissez pas de mots en Anglais dans la traduction finale (sauf pour les noms de marques ou les acronymes sans traduction acceptée, comme CNN ou CBS). Exception Critique : Lorsqu'une seule lettre anglaise apparaît pour décrire une forme ou un objet (ex : La pièce en "I", en forme de V), vous devez translittérer le nom de la lettre en Français. Ne laissez jamais les lettres anglaises dans la sortie.

### [IDX_CLEAN]. Règles de Nettoyage et de Formatage (DOIT s'appliquer à la sortie JSON finale) ###
1. Supprimer les Étiquettes de Locuteur : Supprimez complètement les étiquettes d'identification des locuteurs qui apparaissent au début d'un sous-titre et se terminent par deux points (ex : "PROBST:", "JEFF:"). Vous devez vous assurer que le nom du locuteur ne reste pas dans la traduction finale.
2. Nettoyer les Éléments Sonores (SDH) : Supprimez les descriptions sonores entre crochets [] ou parenthèses () (ex : [acclamations], (tousse)). **Important :** Si le texte à l'intérieur des parenthèses est un dialogue parlé (ex : chuchotement), vous devez le traduire et garder les parenthèses.
3. Sauts de ligne (\\n) : Vous devez diviser les phrases longues ! Si le texte traduit pour un index spécifique dépasse {max_words} mots, vous devez utiliser le caractère `\\n` à un endroit syntaxiquement logique pour diviser le texte en deux lignes.""",
    "native_judge_prompt": "Vous êtes un auditeur QA impitoyable pour les traductions de sous-titres en Français.\nLangue source : Anglais. Langue cible : Français.\n\n### RÈGLES DE REJET (rejeter si l'une d'entre elles est VRAIE) :\n1. Omission de texte : La source contient un texte significatif (>2 mots) mais la traduction est vide.\n2. Fuite d'étiquette de locuteur : Une étiquette de locuteur reste dans la traduction (ex : \"JEFF:\" ou sa translittération).\n3. Fuite SDH : Les descripteurs sonores (ex : [musique], (tousse)) restent dans la traduction.\n   EXCEPTION : Le dialogue entre parenthèses (ex : chuchotements) est valide.\n4. Fuite de langue source : Du texte en Anglais apparaît dans la traduction sans justification.\n5. Incohérence des balises : Les balises HTML/de formatage (comme <i>) ne correspondent pas à la source.\n\n### RÈGLES CRITIQUES ANTI-HALLUCINATION :\n- Ignorez les balises de formatage lors de la vérification des fuites d'Anglais.\n- Tous les mots se terminant par deux points ne sont pas des noms de locuteurs.\n- Vérifiez que les erreurs existent dans le texte Français, PAS dans la source Anglaise.\n- Ne PAS halluciner d'erreurs. Vérifiez CHAQUE index individuellement.\n- Si le lot est parfaitement correct, définissez `is_rejected: false`.\n- Si une seule petite erreur est trouvée, définissez `is_rejected: true` et détaillez-la.\n- **Vous devez répondre entièrement en Français.** N'utilisez pas l'Anglais dans votre processus de réflexion.",
    "native_user_prompt_prefix": "Vous traduisez maintenant le lot suivant. Rappel : La sortie doit être en Français uniquement.",
    "native_special_instructions_header": "### Instructions Spéciales pour ce Lot (Votre Responsabilité !) ###",
    "native_technical_rules_header": "### Règles Techniques Obligatoires ###",
    "native_exact_count_rule": "1. Compte Exact : **Vous devez renvoyer exactement {expected_count} clés dans l'objet 'translated_srt'.**",
    "native_exact_indices_rule": "2. Index Exacts : Utilisez EXACTEMENT les index suivants comme clés : {indices}.",
    "native_do_not_translate_rule": "3. **NE TRADUISEZ PAS et N'INCLUEZ PAS** de mot apparaissant dans les blocs de \"Contexte\" (dans n'importe quel champ).",
    "native_missing_translation_label": "Traduction manquante",
    "native_tag_rule": "4. Balises de Formatage : Conservez les balises comme <i> ou <font color=\"...\"> exactement dans leur position d'origine. Ne traduisez pas les mots techniques (comme 'color') et ne les supprimez pas. **Important : Vous êtes autorisé (et tenu) d'ajouter un saut de ligne `\\n` à l'intérieur des balises (ex : `<i>texte...\\n...texte</i>`) pour maintenir la règle des {max_words} mots par ligne.** Assurez-vous que les valeurs de couleur sont entourées de guillemets.",
    "native_schema_descriptions": {
        "thought_process": "Le processus de réflexion, la stratégie et les délibérations avant la traduction finale. Attention : Ne copiez pas la description du champ ! Écrivez vos vraies pensées.",
        "summary": "Un bref résumé de ce qui se passe actuellement dans l'intrigue. Attention : Ne copiez pas la description du champ ! Écrivez un vrai résumé.",
        "continuous_translation_draft": "Traduisez tous les textes comme un seul paragraphe continu, naturel et fluide.",
        "mapping_plan": "Un plan de cartographie concis divisant le brouillon en index.",
        "translated_srt": "Un dictionnaire où les clés sont des index numériques et les valeurs sont les traductions finales en Français.",
        "last_speaker_info": "Le nom du locuteur (M/F) s'adressant à une cible (M/F/Inconnu/Caméra).",
        "continuity_note": "Instruction de continuité pour le prochain lot (laisser vide si aucune).",
        "judge_thought_process": "Mandatoire : Écrivez au moins une phrase en Français analysant la traduction par rapport à la source. Expliquez exactement pourquoi vous avez décidé de rejeter ou d'approuver. N'utilisez pas de '...'.",
        "judge_summary": "Un bref résumé (une phrase) de l'intrigue. N'utilisez pas de '...'.",
        "judge_is_valid": "True si la traduction est parfaite. False si elle doit être rejetée (Règles 1-6).",
        "judge_error_map": "Cartographie des index aux erreurs. Mandatoire de fournir un raisonnement en Français pour chaque rejet. Pour une traduction valide, laissez une chaîne vide \"\"."
    },
    "native_judge_strings": {
        "overlap_header": "### [CONTEXTE EN LECTURE SEULE] (RÉFÉRENCE UNIQUEMENT - NE PAS AUDITER CES LIGNES) ###",
        "overlap_desc": "Ne rejetez pas les lignes OVERLAP ; utilisez-les uniquement pour comprendre si des informations ont « fui » vers un sous-titre adjacent dans le lot audité.",
        "overlap_none": "(Aucun — limite du fichier)",
        "overlap_missing_context": "(Contexte externe non fourni.)",
        "overlap_cannot_resolve": "(Impossible de résoudre les voisins — index manquant dans la liste de commande.)",
        "overlap_pre_batch": "Une ligne avant le début du chunk (Informations pré-lot)",
        "overlap_post_batch": "Une ligne après la fin du chunk (Informations post-lot)",
        "overlap_not_translated": "Cette ligne n'a pas encore été traduite - ne la rejetez pas pour cette raison - vous auditez uniquement la traduction des lignes précédentes",
        "source_label": "Source ({lang}) :",
        "target_label": "Traduction ({lang}) :",
        "chunk_header": "### CHUNK D'AUDIT {current}/{total} (Blocs : {start}-{end}) ###",
        "automated_warning_header": "### AVERTISSEMENT D'AUDIT SYSTÈME AUTOMATISÉ : ###",
        "automated_warning_desc": "NOTE : Un algorithme automatisé a signalé une erreur potentielle ci-dessus. Examinez attentivement l'index spécifié. Exercez votre jugement indépendant - l'algorithme pourrait se tromper (ex : différences de longueur naturelles entre les langues). Ne rejetez que si vous voyez une erreur réelle et matérielle de vos propres yeux.",
        "end_of_data": "### FIN DES DONNÉES ###",
        "final_warning": "AVERTISSEMENT FINAL : Rejetez le lot (`is_rejected: true`) UNIQUEMENT si vous voyez l'erreur de vos propres yeux dans le champ Traduction ({lang}). NE REJETEZ PAS si l'erreur n'existe que dans la Source ({source}).",
        "field_desc_thought": "Analyse approfondie (minimum une phrase complète). Expliquez exactement ce que vous avez vérifié. N'utilisez pas '...'.",
        "field_desc_summary": "Bref résumé de l'intrigue. N'utilisez pas '...'.",
        "field_desc_is_rejected": "True si rejeté (erreur trouvée). False si totalement impeccable.",
        "field_desc_error_map": "Description de l'erreur (phrase complète). Laissez vide si impeccable."
    },
    "native_index_label": "Index",
    "native_feedback_header": "### VOUS DEVEZ CORRIGER LES ERREURS SUIVANTES PAR INDEX (NE RÉPÉTEZ PAS CES ERREURS) : ###",
    "native_last_line_label": "Dernière ligne traduite (du lot précédent) : '{last_line}'",
    "native_continuity_note_label": "⚠️ Note de continuité du lot précédent (Attention !) : {note}",
    "native_story_context_header": "### Contexte de l'histoire (lots précédents) ###",
    "native_current_setting_label": "Cadre actuel : {setting}",
    "native_plot_summary_label": "Résumé de l'intrigue : {summary}",
    "native_last_speaker_label": "Dernier locuteur (lot précédent) : {speaker}",
    "native_schema_mandatory_label": "### OBLIGATOIRE : Répondez EXACTEMENT au format JSON Schema spécifié. ###",
    "native_placeholder_indicators": ["<insérez ici", "<doit être rempli", "<la traduction finale", "<nom du locuteur", "<instruction de continuité"],
    "native_robot_phrases": ["Voici la traduction", "Ici apparaît", "Traduction :", "Le sous-titre suivant"],
    "native_exempt_labels": ["Note", "Attention", "PS"],
    "native_intervention_header": "####### INTERVENTION MANUELLE REQUISE #######",
    "native_intervention_instructions": [
        "Instructions :",
        "1. Modifiez la traduction au mieux de vos capacités.",
        "2. Enregistrez le fichier (Ctrl+S).",
        "3. Fermez l'éditeur pour continuer."
    ],
    "native_intervention_source_label": "LIGNES SOURCES ANGLAISES",
    "native_intervention_target_label": "LIGNES TRADUITES NÉCESSITANT UNE CORRECTION",
    "native_intervention_edit_warning": "Ne modifiez pas les numéros d'index, seulement le texte de la traduction.",
    "native_intervention_max_words_warning": "Essayez de ne pas dépasser {max_words} mots par ligne.",
    "native_intervention_error_label": "Les erreurs identifiées dans ces lignes sont :",
    "label_prev_context": "Contexte Précédent",
    "label_translation_blocks": "Blocs de Traduction - JSON",
    "label_next_context": "Contexte Suivant",
    "native_do_not_translate_label": "PAS À TRADUIRE",
    "native_overlong_word": "mots",
    "native_overlong_phrase": "trop longue",
    "native_missing_translation_label": "Traduction manquante"
}
